name: image-template-search

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip:
      - exif==1.6.0
      - fiftyone==1.0.1
      - fiftyone-brain==0.17.0
      - fiftyone-db==1.1.7
      - fiona==1.9.6
      - hydra-core==1.3.2
      - kornia==0.7.3
      - kornia-rs==0.1.5
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - pydantic==2.7.4
      - shapely==2.0.4
