name: pytest

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-22.04]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: image-template-search
        environment-file: environment.yml
        auto-update-conda: true
        auto-activate-base: false

    - name: Install additional dependencies
      run: |
        conda install pytest

    - name: Run pytest
      run: |
        pytest tests/ --maxfail=1 --disable-warnings
