name: pytest

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: image-template-search
        auto-update-conda: true
        auto-activate-base: false

    - name: Install conda dependencies
      run: |
        conda install -c conda-forge gdal geopandas pytest

    - name: Install pip dependencies
      run: |
        pip install -r requirements.txt

    - name: Run pytest
      run: |
        pytest tests/ --maxfail=1 --disable-warnings