name: Run Tests

on:
  push:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/python-gdal:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify environment
      run: |
        python -c "from osgeo import gdal; print(f'GDAL version: {gdal.__version__}')"
        python -c "import torch; print(f'PyTorch version: {torch.__version__}')"

    - name: Run tests
      run: |
        pytest -v --cov=. --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

    - name: Run flake8
      run: |
        flake8 image_template_search --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 image_template_search --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics